# Generated by Django 2.0.2 on 2018-05-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantlocation_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantsLocation',
        ),
    ]
